const actions = {
  GETTING_WEDDING_PAYMENT_HISTORY: "GETTING_WEDDING_PAYMENT_HISTORY",
  WEDDING_PAYMENT_HISTORY_GET_SUCCESS: 'WEDDING_PAYMENT_HISTORY_GET_SUCCESS',
  WEDDING_PAYMENT_HISTORY_GET_ERROR: 'WEDDING_PAYMENT_HISTORY_GET_ERROR',
  GETTING_ENGAGEMENT_PAYMENT_HISTORY: "GETTING_ENGAGEMENT_PAYMENT_HISTORY",
  ENGAGEMENT_PAYMENT_HISTORY_GET_SUCCESS: 'ENGAGEMENT_PAYMENT_HISTORY_GET_SUCCESS',
  ENGAGEMENT_PAYMENT_HISTORY_GET_ERROR: 'ENGAGEMENT_PAYMENT_HISTORY_GET_ERROR',
  getWeddingPaymentHistory: payload => ({
      type: actions.GETTING_WEDDING_PAYMENT_HISTORY,
      payload
  }),
  getEngagementPaymentHistory: payload => ({
      type: actions.GETTING_ENGAGEMENT_PAYMENT_HISTORY,
      payload
  })

}

export default actions