const actions = {
  GET_PENDING_CONTRACT: "GET_PENDING_CONTRACT",
  GET_PENDING_CONTRACT_SUCCESS: "GET_PENDING_CONTRACT_SUCCESS",
  GET_PENDING_CONTRACT_ERROR: "GET_PENDING_CONTRACT_ERROR",
  GET_SIGNED_CONTRACT: "GET_SIGNED_CONTRACT",
  GET_SIGNED_CONTRACT_SUCCESS: "GET_SIGNED_CONTRACT_SUCCESS",
  GET_SIGNED_CONTRACT_ERROR: "GET_SIGNED_CONTRACT_ERROR",
  GET_CONTRACT_DETAIL: 'GET_CONTRACT_DETAIL',
  GET_CONTRACT_DETAIL_SUCCESS: 'GET_CONTRACT_DETAIL_SUCCESS',
  GET_CONTRACT_DETAIL_ERROR: 'GET_CONTRACT_DETAIL_ERROR',

  getPendingContract: payload => ({
    type: actions.GET_PENDING_CONTRACT,
    payload
  })
}
export default actions