const actions = {
  WEDDING_PAYMENT_REQUEST: "WEDDING_PAYMENT_REQUEST",
  WEDDING_PAYMENT_REQUEST_SUCCESS: "WEDDING_PAYMENT_REQUEST_SUCCESS",
  WEDDING_PAYMENT_REQUEST_ERROR: "WEDDING_PAYMENT_REQUEST_ERROR",
  ENGAGEMENT_PAYMENT_REQUEST: "ENGAGEMENT_PAYMENT_REQUEST",
  ENGAGEMENT_PAYMENT_REQUEST_SUCCESS: "ENGAGEMENT_PAYMENT_REQUEST_SUCCESS",
  ENGAGEMENT_PAYMENT_REQUEST_ERROR: "ENGAGEMENT_PAYMENT_REQUEST_ERROR",
  IF_SECOND_SHOOTER: 'IF_SECOND_SHOOTER',
  SECOND_SHOOTER_DETAIL: 'SECOND_SHOOTER_DETAIL',
  REQUEST_WEDDING_PAY: 'REQUEST_WEDDING_PAY',
  REQUEST_WEDDING_PAY_SUCCESS: 'REQUEST_WEDDING_PAY_SUCCESS',
  REQUEST_WEDDING_PAY_ERROR: 'REQUEST_WEDDING_PAY_ERROR',
  REQUEST_ENGAGEMENT_PAY: 'REQUEST_ENGAGEMENT_PAY',
  REQUEST_ENGAGEMENT_PAY_SUCCESS: 'REQUEST_ENGAGEMENT_PAY_SUCCESS',
  REQUEST_ENGAGEMENT_PAY_ERROR: 'REQUEST_ENGAGEMENT_PAY_ERROR',
  NEXT_STEP: 'NEXT_STEP',
  requestWeddingPayment: payload => ({
    type: actions.WEDDING_PAYMENT_REQUEST,
    payload
  }),
  ifSecondShooter:  payload => ({
    type: actions.IF_SECOND_SHOOTER,
    payload
  }),
  secondShooterDetail: payload => ({
    type: actions.SECOND_SHOOTER_DETAIL,
    payload
  }),
  requestWeddingPay: payload => ({
    type: actions.REQUEST_WEDDING_PAY,
    payload
  }),
  requestEngagementPay: payload => ({
    type: actions.REQUEST_ENGAGEMENT_PAY,
    payload
  }),
  requestEngagementPayment:  payload => ({
    type: actions.ENGAGEMENT_PAYMENT_REQUEST,
    payload
  }),
  nextStep:  payload => ({
    type: actions.NEXT_STEP,
    payload
  })
}

export default actions